[tasks.run]
script = '''
docker compose up --build
'''

[tasks.upgrade-all]
script = '''
makers upgrade tsconfig
makers upgrade frontend-tsconfig
makers upgrade eslint-config
makers upgrade frontend-eslint-config
makers upgrade prettier-config
makers upgrade stylelint-config
'''

[tasks.upgrade]
script = '''
cd ./packages/${@}
npx npm-check-updates -u
'''
